# Generated by Django 4.0.6 on 2022-08-05 20:29

import apps.projects.api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_areasmodel_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(default='2022-08-05', verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name_calendar', models.CharField(max_length=50, verbose_name='Nombre del Calendario')),
                ('date_delivery_stage_1', models.DateField(verbose_name='Fecha Entrega Etapa 1')),
                ('date_delivery_stage_2', models.DateField(verbose_name='Fecha Entrega Etapa 2')),
                ('date_delivery_stage_3', models.DateField(verbose_name='Fecha Entrega Etapa 3')),
                ('date_delivery_stage_4', models.DateField(verbose_name='Fecha Entrega Etapa 4')),
                ('date_delivery_stage_5', models.DateField(verbose_name='Fecha Entrega Etapa 5')),
                ('date_delivery_stage_6', models.DateField(verbose_name='Fecha Entrega Etapa 6')),
                ('date_delivery_stage_7', models.DateField(verbose_name='Fecha Entrega Etapa 7')),
                ('date_delivery_stage_8', models.DateField(verbose_name='Fecha Entrega Etapa 8')),
                ('date_delivery_stage_9', models.DateField(verbose_name='Fecha Entrega Etapa 9')),
                ('date_delivery_stage_10', models.DateField(verbose_name='Fecha Entrega Etapa 10')),
                ('date_delivery_stage_11', models.DateField(verbose_name='Fecha Entrega Etapa 11')),
                ('date_delivery_stage_12', models.DateField(verbose_name='Fecha Entrega Etapa 11')),
            ],
            options={
                'verbose_name': 'CalendarModel',
                'verbose_name_plural': 'CalendarModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgressreportModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(default='2022-08-05', verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('dateinitial', models.DateField(verbose_name=apps.projects.api.models.ProjectsModel)),
                ('datecompletion', models.DateField(verbose_name=apps.projects.api.models.ProjectsModel)),
                ('adminproject', models.CharField(max_length=50, verbose_name='Responsable')),
                ('auditorproject', models.CharField(max_length=50, verbose_name='Responsable')),
                ('leaderproject', models.CharField(max_length=50, verbose_name='Responsable')),
                ('notes', models.CharField(max_length=200, verbose_name='Notas')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.companiesmodel', verbose_name='Company Name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectsmodel', verbose_name='Project Name')),
            ],
            options={
                'verbose_name': 'ProgressreportModel',
                'verbose_name_plural': 'ProgressreportModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarAdmin',
            fields=[
                ('calendarmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metrics.calendarmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('metrics.calendarmodel',),
        ),
        migrations.CreateModel(
            name='IndicatorsModel',
            fields=[
                ('progressreportmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metrics.progressreportmodel')),
                ('nameIndicator', models.CharField(max_length=50, verbose_name='Nombre del Informe')),
                ('stages_completed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Etapas Completadas')),
                ('activities_completed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Actividades Completadas')),
                ('controls_completed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Controles Completadas')),
                ('risks_completed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Riesgos Completadas')),
                ('threats_completed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Amenazas Completadas')),
                ('results_completed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Resultados Completadas')),
            ],
            options={
                'verbose_name': 'IndicatorsModel',
                'verbose_name_plural': '"IndicatorsModels',
                'ordering': ['-id'],
            },
            bases=('metrics.progressreportmodel',),
        ),
        migrations.CreateModel(
            name='ProgressreportAdmin',
            fields=[
                ('progressreportmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metrics.progressreportmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('metrics.progressreportmodel',),
        ),
        migrations.CreateModel(
            name='IndicatorsAdmin',
            fields=[
                ('indicatorsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metrics.indicatorsmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('metrics.indicatorsmodel',),
        ),
    ]
