# Generated by Django 4.0.6 on 2022-08-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreasModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name_area', models.CharField(max_length=50, verbose_name='Nombre del Area')),
                ('notes_area', models.CharField(max_length=200, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'AreasModel',
                'verbose_name_plural': 'AreasModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CompaniesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('comercial_name', models.CharField(max_length=50, verbose_name='Razon Social')),
                ('nit', models.CharField(max_length=11, verbose_name='Nit')),
                ('slogan', models.CharField(max_length=100, verbose_name='Slogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Logotipo')),
                ('number_of_areas', models.IntegerField(verbose_name='Cantidad de Areas')),
                ('amount_of_assets', models.IntegerField(verbose_name='Cantidad de Activos')),
                ('notes_company', models.CharField(max_length=200, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'CompaniesModel',
                'verbose_name_plural': 'CompaniesModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('nameproject', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Proyecto')),
                ('budget', models.IntegerField(verbose_name='Presupuesto en pesos')),
                ('objetives', models.TextField(verbose_name='Objetivos del Proyecto')),
                ('number_of_stages', models.IntegerField(verbose_name='Cantidad de Etapas')),
                ('dateinitial', models.DateField(verbose_name='Fecha Inicio de Proyecto')),
                ('datecompletion', models.DateField(verbose_name='Fecha Inicio de Proyecto')),
                ('current_month', models.IntegerField(verbose_name='Mes en curso del prouecto')),
                ('adminproject', models.CharField(max_length=50, verbose_name='Responsable')),
                ('auditorproject', models.CharField(max_length=50, verbose_name='Responsable')),
                ('leaderproject', models.CharField(max_length=50, verbose_name='Responsable')),
                ('percentage_of_progress', models.IntegerField(verbose_name='Porcentaje de Avance')),
            ],
            options={
                'verbose_name': 'ProjectsModel',
                'verbose_name_plural': 'ProjectsModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StagesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('comercial_name', models.CharField(max_length=50, verbose_name='Nombre de la Etapa')),
                ('number_stage', models.IntegerField(choices=[('primera', 'Primera'), ('segunda', 'Segunda'), ('tercera', 'Tercera'), ('cuarta', 'Cuarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta'), ('septima', 'Septima'), ('octava', 'Octava'), ('novena', 'Novena'), ('decima', 'Decima'), ('undecima', 'Undecima'), ('duodecima', 'Duodecima')], default=1, verbose_name='Cantidad de Etapas')),
                ('type', models.CharField(choices=[('primera', 'Primera'), ('segunda', 'Segunda'), ('tercera', 'Tercera'), ('cuarta', 'Cuarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta'), ('septima', 'Septima'), ('octava', 'Octava'), ('novena', 'Novena'), ('decima', 'Decima'), ('undecima', 'Undecima'), ('duodecima', 'Duodecima')], default='Ninguna', max_length=20, verbose_name='Tipo de Actividad')),
                ('date_dalivery_stage', models.DateField(auto_now_add=True, verbose_name='Fecha Entrega Etapa 1')),
            ],
            options={
                'verbose_name': 'StagesModel',
                'verbose_name_plural': 'StagesModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AreasAdmin',
            fields=[
                ('areasmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.areasmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('projects.areasmodel',),
        ),
        migrations.CreateModel(
            name='CompaniesAdmin',
            fields=[
                ('companiesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.companiesmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('projects.companiesmodel',),
        ),
        migrations.CreateModel(
            name='ProjectsAdmin',
            fields=[
                ('projectsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.projectsmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('projects.projectsmodel',),
        ),
        migrations.CreateModel(
            name='StagesAdmin',
            fields=[
                ('stagesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.stagesmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('projects.stagesmodel',),
        ),
        migrations.AddField(
            model_name='companiesmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectsmodel', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='areasmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.companiesmodel', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='areasmodel',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectsmodel', verbose_name='Lider de Area'),
        ),
    ]
