# Generated by Django 4.0.6 on 2022-08-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagesmodel',
            name='type',
            field=models.CharField(default=1, max_length=20, verbose_name='Tipo de Etapa'),
        ),
    ]
