# Generated by Django 4.0.6 on 2022-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_stagesmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='companiesmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='stagesmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='stagesmodel',
            name='date_dalivery_stage',
            field=models.DateField(verbose_name='Fecha Entrega Etapa 1'),
        ),
    ]
