# Generated by Django 4.0.6 on 2022-08-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectsmodel_adminproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsmodel',
            old_name='nameproject',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='current_month',
            field=models.IntegerField(verbose_name='Mes en curso del proyecto'),
        ),
    ]
