# Generated by Django 4.0.6 on 2022-08-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_areasmodel_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companiesmodel',
            old_name='comercial_name',
            new_name='name',
        ),
    ]
