# Generated by Django 4.0.6 on 2022-08-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_comercial_name_companiesmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Razon Social '),
        ),
    ]
