# Generated by Django 4.0.6 on 2022-08-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_companiesmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areasmodel',
            old_name='name_area',
            new_name='name',
        ),
    ]
