# Generated by Django 4.0.6 on 2022-08-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_name_area_areasmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagesmodel',
            name='type',
            field=models.CharField(default=1, max_length=30, verbose_name='Tipo de Etapa'),
        ),
    ]
