# Generated by Django 4.0.6 on 2022-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_stagesmodel_number_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagesmodel',
            name='number_stage',
            field=models.CharField(choices=[('------', '------'), ('primera', 'Primera'), ('segunda', 'Segunda'), ('tercera', 'Tercera'), ('cuarta', 'Cuarta'), ('quinta', 'Quinta'), ('sexta', 'Sexta'), ('septima', 'Septima'), ('octava', 'Octava'), ('novena', 'Novena'), ('decima', 'Decima'), ('undecima', 'Undecima'), ('duodecima', 'Duodecima')], max_length=30, verbose_name='Nivel de Progreso'),
        ),
    ]
