# Generated by Django 4.0.6 on 2022-08-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_stagesmodel_number_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stagesmodel',
            old_name='comercial_name',
            new_name='name',
        ),
    ]
