# Generated by Django 4.0.6 on 2022-08-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_stagesmodel_number_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagesmodel',
            name='type',
            field=models.CharField(default=1, max_length=70, verbose_name='Tipo de Etapa'),
        ),
    ]
