# Generated by Django 4.0.6 on 2022-08-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name_help', models.CharField(max_length=50, verbose_name='Nombre del Calendario')),
                ('description_help', models.TextField(max_length=200, verbose_name='Descripcion General')),
            ],
            options={
                'verbose_name': 'HelpsModel',
                'verbose_name_plural': 'HelpsModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HelpsAdmin',
            fields=[
                ('helpsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.helpsmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('resources.helpsmodel',),
        ),
        migrations.CreateModel(
            name='ResourcecategoryModel',
            fields=[
                ('helpsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.helpsmodel')),
                ('cateogry', models.CharField(choices=[('link', 'Link'), ('video', 'Video'), ('imagen', 'Imagen'), ('contacto', 'Contacto'), ('adjunto', 'Adjunto')], default='Ninguna', max_length=50, verbose_name='Categoria de Recursos')),
            ],
            options={
                'verbose_name': 'ResourcecategoryModel',
                'verbose_name_plural': 'ResourcecategoryModels',
                'ordering': ['-id'],
            },
            bases=('resources.helpsmodel',),
        ),
        migrations.CreateModel(
            name='ResourcecategoryAdmin',
            fields=[
                ('resourcecategorymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resourcecategorymodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('resources.resourcecategorymodel',),
        ),
        migrations.CreateModel(
            name='ResourcesModel',
            fields=[
                ('resourcecategorymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resourcecategorymodel')),
                ('title_resource', models.CharField(max_length=50, verbose_name='Titulo del Recurso')),
                ('description_resource', models.CharField(max_length=200, verbose_name='Descripcion del Recurso')),
                ('image_resource', models.ImageField(blank=True, null=True, upload_to='resources/', verbose_name='Logotipo')),
                ('link_resource', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'ResourcesModel',
                'verbose_name_plural': 'ResourcesModels',
                'ordering': ['-id'],
            },
            bases=('resources.resourcecategorymodel',),
        ),
        migrations.CreateModel(
            name='ResourcesAdmin',
            fields=[
                ('resourcesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resources.resourcesmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('resources.resourcesmodel',),
        ),
    ]
