# Generated by Django 4.0.6 on 2022-08-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecategorymodel',
            name='cateogry',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('link', 'Link'), ('video', 'Video'), ('imagen', 'Imagen'), ('contacto', 'Contacto'), ('adjunto', 'Adjunto')], default=1, max_length=50, verbose_name='Categoria de Recursos'),
        ),
    ]
