# Generated by Django 4.0.6 on 2022-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resourcecategorymodel_cateogry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpsmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
    ]
