# Generated by Django 4.0.6 on 2022-08-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title_standard', models.CharField(max_length=50, verbose_name='Titulo de la Documentacion')),
                ('version_standard', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'StandardsModel',
                'verbose_name_plural': 'StandardsModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChaptersModel',
            fields=[
                ('standardsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='standards.standardsmodel')),
                ('title_chapter', models.CharField(max_length=50, verbose_name='Titulo del Capitulo')),
                ('description_chapter', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('image_chapter', models.ImageField(blank=True, null=True, upload_to='standards/', verbose_name='Imagen')),
                ('link_chapter', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'ChaptersModel',
                'verbose_name_plural': 'ChaptersModels',
                'ordering': ['-id'],
            },
            bases=('standards.standardsmodel',),
        ),
        migrations.CreateModel(
            name='StandardsAdmin',
            fields=[
                ('standardsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='standards.standardsmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('standards.standardsmodel',),
        ),
        migrations.CreateModel(
            name='ArticlesModel',
            fields=[
                ('chaptersmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='standards.chaptersmodel')),
                ('title_article', models.CharField(max_length=50, verbose_name='Titulo del Capitulo')),
                ('description_article', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('image_article', models.ImageField(blank=True, null=True, upload_to='standards/', verbose_name='Imagen')),
                ('link_article', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'ArticlesModel',
                'verbose_name_plural': 'ArticlesModels',
                'ordering': ['-id'],
            },
            bases=('standards.chaptersmodel',),
        ),
        migrations.CreateModel(
            name='ChaptersAdmin',
            fields=[
                ('chaptersmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='standards.chaptersmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('standards.chaptersmodel',),
        ),
        migrations.CreateModel(
            name='ArticlesAdmin',
            fields=[
                ('articlesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='standards.articlesmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('standards.articlesmodel',),
        ),
    ]
