# Generated by Django 4.0.6 on 2022-08-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Activo')),
                ('type', models.CharField(choices=[('fisico', 'Fisico'), ('informatico', 'Informatico'), ('servicio', 'Servicio'), ('personal', 'Personal')], default='Ninguna', max_length=20, verbose_name='Tipo del Activo')),
                ('appraisal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Avaluo')),
                ('description', models.TextField(max_length=200, verbose_name='Descripcion General')),
                ('location', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Activo')),
                ('substate', models.CharField(choices=[('fisico', 'Fisico'), ('informatico', 'Informatico'), ('servicio', 'Servicio'), ('personal', 'Personal')], default='Ninguna', max_length=20, verbose_name='Tipo del Activo')),
                ('Creacion', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.companiesmodel', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'AssetsModel',
                'verbose_name_plural': 'AssetsModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InformationassetsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo del Activo Informatico')),
                ('notes', models.CharField(max_length=200, verbose_name='Notas')),
                ('imageUpload', models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='Imagen Adjunta')),
                ('delegated', models.CharField(max_length=50, verbose_name='Responsable')),
                ('check_verify', models.BooleanField(default=False)),
                ('corrected', models.BooleanField(default=False)),
                ('managed', models.BooleanField(default=False)),
                ('category_assets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.assetsmodel', verbose_name='Categoria de Activo')),
            ],
            options={
                'verbose_name': 'InformationassetsModel',
                'verbose_name_plural': 'InformationassetsModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PersonalassetsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo del Activo Personal')),
                ('notes', models.CharField(max_length=200, verbose_name='Notas')),
                ('imageUpload', models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='Imagen Adjunta')),
                ('delegated', models.CharField(max_length=50, verbose_name='Responsable')),
                ('check_verify', models.BooleanField(default=False)),
                ('corrected', models.BooleanField(default=False)),
                ('managed', models.BooleanField(default=False)),
                ('category_assets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.assetsmodel', verbose_name='Categoria de Activo')),
            ],
            options={
                'verbose_name': 'PersonalassetsModel',
                'verbose_name_plural': 'PersonalassetsModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalassetsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo del Activo Fisico')),
                ('notes', models.CharField(max_length=200, verbose_name='Notas')),
                ('imageUpload', models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='Imagen Adjunta')),
                ('delegated', models.CharField(max_length=50, verbose_name='Responsable')),
                ('check_verify', models.BooleanField(default=False)),
                ('corrected', models.BooleanField(default=False)),
                ('managed', models.BooleanField(default=False)),
                ('category_assets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.assetsmodel', verbose_name='Categoria de Activo')),
            ],
            options={
                'verbose_name': 'PhysicalassetsModel',
                'verbose_name_plural': 'PhysicalassetsModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceassetsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo del Activo Servicio')),
                ('notes', models.CharField(max_length=200, verbose_name='Notas')),
                ('imageUpload', models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='Imagen Adjunta')),
                ('delegated', models.CharField(max_length=50, verbose_name='Responsable')),
                ('check_verify', models.BooleanField(default=False)),
                ('corrected', models.BooleanField(default=False)),
                ('managed', models.BooleanField(default=False)),
                ('category_assets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.assetsmodel', verbose_name='Categoria de Activo')),
            ],
            options={
                'verbose_name': 'ServiceassetsModel',
                'verbose_name_plural': 'ServiceassetsModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetsAdmin',
            fields=[
                ('assetsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.assetsmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('assets.assetsmodel',),
        ),
        migrations.CreateModel(
            name='InformationassetsAdmin',
            fields=[
                ('informationassetsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.informationassetsmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('assets.informationassetsmodel',),
        ),
        migrations.CreateModel(
            name='PersonalassetsAdmin',
            fields=[
                ('personalassetsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.personalassetsmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('assets.personalassetsmodel',),
        ),
        migrations.CreateModel(
            name='PhysicalassetsAdmin',
            fields=[
                ('physicalassetsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.physicalassetsmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('assets.physicalassetsmodel',),
        ),
        migrations.CreateModel(
            name='ServiceassetsAdmin',
            fields=[
                ('serviceassetsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.serviceassetsmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('assets.serviceassetsmodel',),
        ),
    ]
