# Generated by Django 4.0.6 on 2022-08-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsmodel',
            name='substate',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('fisico', 'Fisico'), ('informatico', 'Informatico'), ('servicio', 'Servicio'), ('personal', 'Personal')], default=1, max_length=20, verbose_name='Tipo del Activo'),
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='type',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('fisico', 'Fisico'), ('informatico', 'Informatico'), ('servicio', 'Servicio'), ('personal', 'Personal')], default=1, max_length=20, verbose_name='Tipo del Activo'),
        ),
    ]
