# Generated by Django 4.0.6 on 2022-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_assetsmodel_substate_alter_assetsmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsmodel',
            name='Creacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='informationassetsmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='personalassetsmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='physicalassetsmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='serviceassetsmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
    ]
