# Generated by Django 4.0.6 on 2022-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_assetsmodel_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetsmodel',
            old_name='Creacion',
            new_name='creacion',
        ),
        migrations.AlterField(
            model_name='assetsmodel',
            name='substate',
            field=models.CharField(choices=[('ninguna', 'Ninguna'), ('sub estado a', 'Sub Estado A'), ('sub estado c', 'Sub Estado C'), ('sub estado i', 'Sub Estado I'), ('sub estado d', 'Sub Estado D')], default=1, max_length=20, verbose_name='Subestado'),
        ),
    ]
