# Generated by Django 4.0.6 on 2022-08-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_creacion_assetsmodel_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsmodel',
            name='appraisal',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Avaluo'),
        ),
    ]
