# Generated by Django 4.0.6 on 2022-08-04 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name_activity', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Actividad')),
                ('type_act', models.CharField(choices=[('control', 'Control'), ('riesgo', 'Riesgo'), ('amenaza', 'Amenaza'), ('resultado', 'Resultado')], default='Ninguna', max_length=20, verbose_name='Tipo de Actividad')),
                ('referenceISO', models.CharField(max_length=50, verbose_name='Referencia a la Norma')),
                ('description', models.TextField(max_length=200, verbose_name='Descripcion General')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.areasmodel', verbose_name='Area de la Empresa')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ControlsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo del Control')),
                ('notes', models.CharField(max_length=200, verbose_name='Notas')),
                ('imageUpload', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='Imagen Adjunta')),
                ('check_verify', models.BooleanField(default=False)),
                ('corrected', models.BooleanField(default=False)),
                ('managed', models.BooleanField(default=False)),
                ('category_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activitiesmodel', verbose_name='Categoria de Actividad')),
            ],
            options={
                'verbose_name': 'ControlsModel',
                'verbose_name_plural': 'ControlsModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ResultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo del Resultado')),
                ('notes', models.CharField(max_length=200, verbose_name='Notas')),
                ('imageUpload', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='Imagen Adjunta')),
                ('check_verify', models.BooleanField(default=False)),
                ('corrected', models.BooleanField(default=False)),
                ('managed', models.BooleanField(default=False)),
                ('category_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activitiesmodel', verbose_name='Categoria de Actividad')),
            ],
            options={
                'verbose_name': 'ResultsModel',
                'verbose_name_plural': 'ResultsModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RisksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo del Riesgo')),
                ('notes_risk', models.CharField(max_length=200, verbose_name='Notas')),
                ('imageUpload', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='Imagen Adjunta')),
                ('check_verify', models.BooleanField(default=False)),
                ('corrected', models.BooleanField(default=False)),
                ('managed', models.BooleanField(default=False)),
                ('category_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activitiesmodel', verbose_name='Categoria de Actividad')),
            ],
            options={
                'verbose_name': 'RisksModel',
                'verbose_name_plural': 'RisksModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ThreatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo del Amenaza')),
                ('notes_thr', models.CharField(max_length=200, verbose_name='Notas')),
                ('imageUpload', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='Imagen Adjunta')),
                ('check_verify', models.BooleanField(default=False)),
                ('corrected', models.BooleanField(default=False)),
                ('managed', models.BooleanField(default=False)),
                ('category_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activitiesmodel', verbose_name='Categoria de Actividad')),
            ],
            options={
                'verbose_name': 'ThreatsModel',
                'verbose_name_plural': 'ThreatsModels',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityAdmin',
            fields=[
                ('activitiesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.activitiesmodel')),
            ],
            options={
                'verbose_name': 'Modelo Base',
                'verbose_name_plural': 'Modelos Base',
                'abstract': False,
            },
            bases=('activities.activitiesmodel',),
        ),
        migrations.CreateModel(
            name='ControlsAdmin',
            fields=[
                ('controlsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.controlsmodel')),
            ],
            bases=('activities.controlsmodel',),
        ),
        migrations.CreateModel(
            name='ResultsAdmin',
            fields=[
                ('resultsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.resultsmodel')),
            ],
            bases=('activities.resultsmodel',),
        ),
        migrations.CreateModel(
            name='RisksAdmin',
            fields=[
                ('risksmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.risksmodel')),
            ],
            bases=('activities.risksmodel',),
        ),
        migrations.CreateModel(
            name='ThreatsAdmin',
            fields=[
                ('threatsmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activities.threatsmodel')),
            ],
            bases=('activities.threatsmodel',),
        ),
    ]
