# Generated by Django 4.0.6 on 2022-08-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesmodel',
            name='type_act',
            field=models.CharField(choices=[('control', 'Control'), ('riesgo', 'Riesgo'), ('amenaza', 'Amenaza'), ('resultado', 'Resultado')], default=1, max_length=20, verbose_name='Tipo de Actividad'),
        ),
    ]
