# Generated by Django 4.0.6 on 2022-08-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activitiesmodel_type_act'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlsadmin',
            options={'verbose_name': 'Modelo Base', 'verbose_name_plural': 'Modelos Base'},
        ),
        migrations.AlterModelOptions(
            name='resultsadmin',
            options={'verbose_name': 'Modelo Base', 'verbose_name_plural': 'Modelos Base'},
        ),
        migrations.AlterModelOptions(
            name='risksadmin',
            options={'verbose_name': 'Modelo Base', 'verbose_name_plural': 'Modelos Base'},
        ),
        migrations.AlterModelOptions(
            name='threatsadmin',
            options={'verbose_name': 'Modelo Base', 'verbose_name_plural': 'Modelos Base'},
        ),
        migrations.AddField(
            model_name='controlsmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='controlsmodel',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='controlsmodel',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='controlsmodel',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='resultsmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='resultsmodel',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='resultsmodel',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='resultsmodel',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='risksmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='risksmodel',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='risksmodel',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='risksmodel',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='threatsmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='threatsmodel',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AddField(
            model_name='threatsmodel',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='threatsmodel',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='activitiesmodel',
            name='creacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activitiesmodel',
            name='created_date',
            field=models.DateField(default='2022-08-05', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='controlsmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='risksmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='threatsmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
